name: root
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - tqdm
  - numpy
  - matplotlib
  - pandas
  - geopandas
  - scikit-learn
  - scipy
  - requests
  - beautifulsoup4
  - luigi
  - hug
  - pip
  - dask
  - datashader
  - pip:
    - altair==3.0.0